FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY ../../ ./

RUN npx prisma generate

RUN npm run build

FROM node:20-alpine

WORKDIR /app/apps/backend

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./
COPY --from=builder /app/prisma ./prisma

RUN npx prisma generate

ENV PORT=4000
EXPOSE $PORT

CMD ["node", "dist/main"]
